# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c271482de133440d4b4dc17f83a50a8a761c981dbb9300d7c291aba74977b68dffb2a18dd6a1eed2ba7711c2bcc7e16909c0872941b06914b81e74f444553f6e

test:
  secret_key_base: f1d1085956ba8a340c22c6eaf0ebf0d19306cb47cc589746f4429566e96559b04ba5e61f81b5b6bf24859ec5dc7c52e4976fb95a2d392edf062eb92efc9a5c09

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
